### ISSUE TITLE
Incompatibility with firestore 18.0.0

### ISSUE THREAD

**Issue by mirdones** [imperiumlabs/GeoFirestore-Android#13] opened 2019-01-28 21:33 UTC
I updated firestore to version 18.0.0.

Now I am getting the following error:

java.lang.NoSuchMethodError: No virtual method set(Ljava/util/Map;Lcom/google/firebase/firestore/SetOptions;)Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/firestore/DocumentReference; or its super classes (declaration of 'com.google.firebase.firestore.DocumentReference'
        at org.imperiumlabs.geofirestore.GeoFirestore.setLocation(GeoFirestore.java:128)

**Comment by tomergoldst** [comment] 2019-01-31 17:22
Also have issues with version 18.0.0

In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.
1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.google.android.gms:play-services-stats:15.0.1 -> com.google.android.gms:play-services-basement@[
15.0.1], but play-services-basement version was 16.0.1.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.google.firebase:firebase-firestore@18.0.0
-- Project 'app' depends onto com.google.firebase:firebase-core@16.0.1
-- Project 'app' depends onto com.google.android.gms:play-services-places@16.0.0
-- Project 'app' depends onto com.google.firebase:firebase-measurement-connector-impl@16.0.1
-- Project 'app' depends onto com.google.firebase:firebase-common@16.0.4
-- Project 'app' depends onto com.google.firebase:firebase-measurement-connector@16.0.0
-- Project 'app' depends onto com.google.android.gms:play-services-basement@16.0.1
-- Project 'app' depends onto com.google.android.gms:play-services-ads-identifier@15.0.1
-- Project 'app' depends onto com.google.firebase:firebase-auth-interop@16.0.1
-- Project 'app' depends onto com.google.android.gms:play-services-places-placereport@16.0.0
-- Project 'app' depends onto com.google.firebase:firebase-iid@16.0.0
-- Project 'app' depends onto com.google.android.gms:play-services-tasks@16.0.1
-- Project 'app' depends onto com.google.firebase:firebase-analytics@16.0.1
-- Project 'app' depends onto com.google.firebase:firebase-iid-interop@16.0.0
-- Project 'app' depends onto com.google.android.gms:play-services-base@16.0.1
-- Project 'app' depends onto com.google.firebase:firebase-analytics-impl@16.1.1
-- Project 'app' depends onto com.google.android.gms:play-services-maps@16.0.0
-- Project 'app' depends onto com.google.android.gms:play-services-stats@15.0.1
-- Project 'app' depends onto com.github.imperiumlabs:GeoFirestore-Android@v1.1.1

**Comment by 5nicolai** [comment] 2019-02-03 14:53
**i hope this error will be fixed**

**Comment by zoro238** [comment] 2019-02-17 20:07
same problem

**Comment by zoro238** [comment] 2019-02-19 04:24
what sloved ?

**Comment by zoro238** [comment] 2019-02-20 04:58
i am used version 18.0.1

**Comment by future-pirate-king** [comment] 2019-02-20 20:50
this problem got resolved when I downgraded the firestore version to 17.1.2

**Comment by mirdones** [comment] 2019-02-20 21:08
> this problem got resolved when I downgraded the firestore version to 17.1.2

That is not exactly solving the problem.

By the way, this library can work with Firestore up to 17.1.5

**Comment by zoro238** [comment] 2019-02-21 22:52
i tested same error with firestore version to 17.1.2 and  17.1.5

**Comment by future-pirate-king** [comment] 2019-02-22 03:54
> i tested same error with firestore version to 17.1.2 and 17.1.5

Share your app gradle configuration and the error you are facing.

**Comment by zoro238** [comment] 2019-02-22 05:47
apply plugin: 'com.android.application'

android {

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.2.cvcvbb"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
   implementation 'com.github.imperiumlabs:GeoFirestore-Android:v1.1.1'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.h6ah4i.android.widget.verticalseekbar:verticalseekbar:1.0.0'
    implementation 'com.firebase:geofire-android:2.3.1'
    implementation 'com.google.firebase:firebase-database:16.0.6'
    implementation 'com.google.firebase:firebase-firestore:16.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.google.android.gms:play-services-maps:16.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
apply plugin: 'com.google.gms.google-services'

**Comment by zoro238** [comment] 2019-02-22 05:47
and error

///'
Now I am getting the following error:

java.lang.NoSuchMethodError: No virtual method set(Ljava/util/Map;Lcom/google/firebase/firestore/SetOptions;)Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/firestore/DocumentReference; or its super classes (declaration of 'com.google.firebase.firestore.DocumentReference'
at org.imperiumlabs.geofirestore.GeoFirestore.setLocation(GeoFirestore.java:128)

**Comment by AngaKoko** [comment] 2019-04-03 17:00
I still get the error when I try removing GeoFirestore location using `removeLocation("itemId")` methos

**Comment by nminhanh-git** [comment] 2019-04-30 13:31
I have this error with Firestore version 18.2.0 when using setLocation method

**Comment by amitbd1508** [comment] 2019-05-03 07:41
downgrade to 17.1.5 solved my problem.

**Comment by KelvinPac** [comment] 2019-05-11 02:40
Is there no fix for this since January? Is the library still maintained?

**Comment by AngaKoko** [comment] 2019-05-13 07:48
You can set location in using

GeoHash geoHash = new GeoHash(new GeoLocation(mGeoPoint.getLatitude(),
mGeoPoint.getLongitude()));

map.put("g", geoHash.getGeoHashString());
map.put("l", Arrays.asList(mGeoPoint.getLatitude(), mGeoPoint.getLongitude()));

**Comment by scm573** [comment] 2019-05-17 00:16
I think the incompatibility issue should has been resolved already.
Try v1.2.0 or v1.2.1. (Currently the build of v1.3.0 is failing so you cannot import that version from JitPack directly: https://github.com/imperiumlabs/GeoFirestore-Android/issues/23)

**Comment by KelvinPac** [comment] 2019-05-17 07:58
Why don't we have support for other queries as well. maybe also limits?

**Comment by ParryPatel021** [comment] 2019-05-20 11:41
> I think the incompatibility issue should has been resolved already.
> Try v1.2.0 or v1.2.1. (Currently the build of v1.3.0 is failing so you cannot import that version from JitPack directly: #23)

This has resolved my problem by changing the version 1.2.1 as @scm573 told

**Comment by Supercaly** [comment] 2019-06-18 08:54
This problem **is present only in older versions of the library** and is caused by depending in an older version of Firestore, this **issue is solved using a version newer than** ***v1.2.1***.
Follow the README.MD to import the current stable version of the library

**Closed by Supercaly** 2019-06-18 08:54 UTC

**Comment by mirmahfuz99** [comment] 2019-07-07 09:44
upgrade to 19.0.0 solved my problem.
