### ISSUE TITLE
It is not possible to register the location in the database

### ISSUE THREAD

**Issue by morcelicaio** [imperiumlabs/GeoFirestore-Android#29] opened 2019-05-19 02:12 UTC
The cod for register locate:

       CollectionReference collectionUsers = FirebaseFirestore.getInstance().collection("users");
        GeoFirestore geoFirestore = new GeoFirestore(collectionUsers);

        geoFirestore.setLocation("que8B9fxxjcvbC81h32VRjeBSUW2", new GeoPoint(37.7853889, -122.4056973), new GeoFirestore.CompletionListener() {
            @Override
            public void onComplete(Exception exception) {
                if (exception == null) {
                    System.out.println("Location saved!");
                }
            }
        });

When I try to register, I get the following error message:
![erro](https://user-images.githubusercontent.com/21083525/57976913-2c93a280-79c2-11e9-8298-d943d34b60b5.jpg)

java.lang.NoSuchMethodError: No virtual method set(Ljava/util/Map;Lcom/google/firebase/firestore/SetOptions;)Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/firestore/DocumentReference; or its super classes (declaration of 'com.google.firebase.firestore.DocumentReference' appears in /data/app/br.edu.ifsp.scl.googlefirebase-1/split_lib_dependencies_apk.apk:classes2.dex)

What to do in this case?

**Comment by morcelicaio** [comment] 2019-05-19 02:13
This is the same problem of an issue 14

**Comment by Supercaly** [comment] 2019-06-05 07:21
What version of the library are you using? Try the v1.4.0, currently the stable release.

**Comment by Rekodr** [comment] 2019-06-11 15:19
Any update on this. I am facing the same problem.

**Comment by Supercaly** [comment] 2019-06-11 19:27
> Any update on this. I am facing the same problem.
> Seems this issue is not there when using Firestore version 17.1.0 or lower

What version of the library are you using?

**Comment by morcelicaio** [comment] 2019-06-18 06:01
@Rekodr , I solved my problem using this version:
implementation 'com.github.imperiumlabs:GeoFirestore-Android:v1.2.1'

Use this version or lastest.

**Comment by Supercaly** [comment] 2019-07-04 08:55
Close because it's duplicate of issue #13 and can be solved using a newer version of the library (v1.2.1+)

**Closed by Supercaly** 2019-07-04 08:55 UTC
Labels: duplicate
